### PR TITLE
Added utils for checking nodes

### PR DESCRIPTION
**Pull request by Cisplatin**
Some of them (the utils) might not be too useful, I'm not sure - let me know if this is a good idea or not!

### CODE REVIEW

**Comment by duaraghav8** [comment]
@Cisplatin this is MUCH cleaner(I'd like to hear you if you have any opinion on below points)

- We will provide these methods to rule devs and even encourage them. But there could also be a downside - devs might get confused because they end up checking using `type` of some nodes and for other nodes they use util functions. Another type of confusion could be ambiguity (for eg -  "how do I check for an `else` clause? is there as `isElse` util or should I use `isIf` only?" Because checking docs is simply more time consuming, they might resort to checking using `type`). Idk how it turns out, so I think we should introduce these as experimental.

- I can see some major benefits of having utils. 1 especially is that solium will soon be moving to antlr4 based parser (the current solidity parser is the bottleneck and makes solium very slow - the biggest pain point). The new parser might have different `type`s and so these utils can abstract away all those details.

- I think all these utils are better suited to solium (core repo), which in turn, can expose them to both core rules and plugin rules.

**Comment by Cisplatin** [comment]
@duaraghav8 Yeah, the first point is why I asked you about this PR on discord - devs might just resort to checking `type`, like you said, in which case this PR will probably do more harm than good. I agree this should be an experimental PR.

With regards to putting them in the core solium repo, that's also a good point - would you like me to move the `utils` file to there and then change this PR to use that file instead?

**Comment by duaraghav8** [comment]
@Cisplatin Yes, that's the best way to move forward! Please move the utils to solium, expose them & use in this plugin.

- Simply add the util methods inside `ast-utils.js` - https://github.com/duaraghav8/Solium/blob/master/lib/utils/ast-utils.js
- Add these methods' names in `INHERITABLE_METHODS` IN https://github.com/duaraghav8/Solium/blob/master/lib/utils/source-code-utils.js

feel free to use ES6 features

This should expose all util methods to the rules like
```js
create(context) {
    if (context.getSourceCode().isExpression(node)) {
        // blah
    }
}
```

If you feel there's a more intuitive/cleaner way to do this, I'd like to hear it

**Comment by Cisplatin** [comment]
@duaraghav8 Sounds like a clean solution - I'll get working on it!

**Comment by Cisplatin** [comment]
@duaraghav8 Going to close this PR and make a new one that uses Solium's utils to clean-up the rules since this PR has quite a few conflicts now due to refactors and such.

**Pull request closed without merging**
